export default {
    CHANGE_SETTINGS: 'CHANGE_SETTINGS',
    CHANGE_NUM_OF_FLOORS: 'CHANGE_NUM_OF_FLOORS',
    CHANGE_NUM_OF_ELEVATORS: 'CHANGE_NUM_OF_ELEVATORS',
    ORDER_ELEVATOR: 'ORDER_ELEVATOR',
    ARRIVED_TO_FLOOR: 'ARRIVED_TO_FLOOR',
    ADD_ELEVATOR_TASK: 'ADD_ELEVATOR_TASK',
    SET_FLOOR_WAITING_TIME: 'SET_FLOOR_WAITING_TIME',
    REMOVE_ELEVATOR_TASK: 'REMOVE_ELEVATOR_TASK',
    CHANGE_ELEVATOR_CURR_FLOOR: 'CHANGE_ELEVATOR_CURR_FLOOR',
    UNLOCK_ELEVATOR: 'UNLOCK_ELEVATOR',
    REDUCE_FLOOR_WAITING_TIME: 'REDUCE_FLOOR_WAITING_TIME'
}